export const FETCH_USERS = 'fetchUsers'
export const FETCH_USER_BY_ID = 'fetchUserById'
export const FETCH_USER_BY_USERNAME = 'fetchUserByUsername'
export const CREATE_USER = 'createUser'
export const UPDATE_USER = 'updateUser'
export const DISABLE_USER = 'disableUser'
export const CHANGE_PASSWORD = 'changePassword'
export const LOGIN = 'login'
export const REGISTER = 'register'
export const SEND_EMAIL_RESET_PASSWORD = 'sendEmailResetPassword'

export const FETCH_PRODUCTS = 'fetchProducts'
export const FETCH_PRODUCTS_AVAILABLE = 'fetchProductsAvailable'
export const FETCH_PRODUCT_BY_ID = 'fetchProductById'
export const FETCH_PRODUCTS_BY_NAME = 'fetchProductByName'
export const CREATE_PRODUCT = 'createProduct'
export const UPDATE_PRODUCT = 'updateProduct'
export const DISABLE_PRODUCT = 'disableProduct'

export const FETCH_CATEGORY = 'fetchCategory'
export const FETCH_CATEGORY_BY_ID = 'fetchCategoryById'
export const CREATE_CATEGORY = 'createCategory'
export const UPDATE_CATEGORY = 'updateCategory'
export const DELETE_CATEGORY = 'deleteCategory'

export const FETCH_PROMOTIONS = 'fetchPromotions'
export const FETCH_PROMOTION_BY_CODE = 'fetchPromotionByCode'
export const CREATE_PROMOTION = 'createPromotion'
export const UPDATE_PROMOTION = 'updatePromotion'
export const DELETE_PROMOTION = 'deletePromotion'

export const FETCH_POSTS = 'fetchPosts'
export const FETCH_POST_BY_ID = 'fetchPostById'
export const CREATE_POST = 'createPost'
export const UPDATE_POST = 'updatePost'
export const DELETE_POST = 'deletePost'

export const FETCH_ORDERS = 'fetchOrders'
export const CREATE_ORDER = 'createOrder'
export const UPDATE_ORDER = 'updateOrder'
export const DELETE_ORDER = 'deleteOrder'

export const FETCH_ORDER_DETAIL = 'fetchOrderDetails'
export const FETCH_ORDER_DETAIL_BY_ID = 'fetchOrderDetailById'
export const FETCH_ORDER_DETAIL_BY_ORDER_ID = 'fetchOrderDetailByOrderId'
export const CREATE_ORDER_DETAIL = 'createOrderDetail'
export const UPDATE_ORDER_DETAIL = 'updateOrderDetail'
export const CREATE_ORDER_DETAIL_BY_ORDER_ID = 'createOrderDetailByOrderId'
export const UPDATE_ORDER_DETAIL_BY_ORDER_ID = 'updateOrderDetailByOrderId'
export const DELETE_ORDER_DETAIL = 'deleteOrderDetail'

export const FETCH_REVIEWS = 'fetchReviews'
export const FETCH_REVIEW_BY_ID = 'fetchReviewById'
export const CREATE_REVIEW = 'createReview'
export const UPDATE_REVIEW = 'updateReview'